version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:3000"
    environment:
      - APP_PORT=3000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6380:6380"
    command: redis-server --port 6380
